### ISSUE TITLE
`brightbox images list --account xxx` filter fails

### ISSUE THREAD

**Issue by nosnickid** [brightbox/brightbox-cli#97]
`$ brightbox images list -l $my_account` has a paging problem due to local filtering.

`$ brightbox --version`
`brightbox version 2.8.1`

`$ brightbox images list -l $my_account` doesn't seem to show any images - but `$ brightbox images list -l $my_account --show-all` correctly shows them.

if we run `$ brightbox images list` the results are all brightbox images.  So, I assume without --show-all, the API is paging the results and the first page are all BB owned images.

**Comment by tokengeek** [comment]
Thanks for reporting this.

The API call looks correct and with some checking the full list of images are being returned. There is a problem in the command line filter command itself.

It looks like a potential issue with the back-end library used by the CLI is returning a `Hash` with different key types. A previously working reference to an key of `id:Symbol` is now turning up as an `id:String` and the second filter is left comparing `Image#owner_id != nil`

That means in your expected case, this filter is running removing all images related to the account rather than everything else. `-a` disables this second filter to show everything bypassing the bug.

```ruby
      # Remove images that don't belong to the specified owner id
      if options[:l]
        if options[:l] == 'brightbox'
          images.reject! { |i| !i.official }
        else
          images.reject! { |i| i.owner_id != options[:l] }
        end
      end

      unless options[:a]
        account = Account.conn.get_scoped_account(:nested => false)
        images.reject! { |i| !i.official && i.owner_id != account[:id]  }
      end
```

https://github.com/brightbox/brightbox-cli/blob/master/lib/brightbox-cli/images.rb#L33-L45

Changing some key references fixes seems to fix it currently but I need to do a bit more digging to find where the regression was introduced.

**Comment by nosnickid** [comment]
Hi Paul, updated and working perfectly - thanks.

**Comment by tokengeek** [comment]
Thanks!
